"""Phase 3: lifecycle of auto-generated personality files.

A parent (maestro) can include `display_name` and `personality`
on a `spawn_team` action. When both are present, the
ProcessManager writes a personality file with `auto_generated: true`
frontmatter. On kill, only auto-generated files are deleted —
user-authored files (no frontmatter) are always preserved.

Pair-or-nothing: missing either field skips file creation. Existing
files are never overwritten (first parent wins; user-authored files
are protected).

Note: the persistent Worker entity (and the `spawn_worker` action /
lifecycle method) was retired in Ticket 018. `spawn_worker` is now a
generic unknown action — `parse_actions` skips it with an
"Unknown action type" error.
"""

from __future__ import annotations

from pathlib import Path

import pytest_asyncio

from hive.bus.actions import Action, parse_actions
from hive.bus.router import MessageRouter
from hive.models.entity import is_auto_generated_personality, parse_personality
from hive.models.maestro import Maestro
from hive.process.manager import ProcessManager


@pytest_asyncio.fixture
async def lifecycle_manager(router: MessageRouter, tmp_path: Path) -> ProcessManager:
    """Process manager with a tmp_path-backed personalities dir."""
    mgr = ProcessManager(router=router, personalities_dir=tmp_path)
    yield mgr
    await mgr.kill_all()


class TestIsAutoGeneratedHelper:
    """Pure-function helper that decides whether a file may be deleted."""

    def test_returns_true_when_frontmatter_flag_present(self, tmp_path: Path) -> None:
        p = tmp_path / "auto.md"
        p.write_text("---\nauto_generated: true\n---\n# Entity: Auto\n## Identity\n")
        assert is_auto_generated_personality(p) is True

    def test_returns_false_when_no_frontmatter(self, tmp_path: Path) -> None:
        p = tmp_path / "user.md"
        p.write_text("# Entity: User\n## Identity\n- **Name**: User\n")
        assert is_auto_generated_personality(p) is False

    def test_returns_false_when_frontmatter_flag_false(self, tmp_path: Path) -> None:
        p = tmp_path / "manual.md"
        p.write_text("---\nauto_generated: false\n---\n# Entity\n")
        assert is_auto_generated_personality(p) is False

    def test_returns_false_when_file_missing(self, tmp_path: Path) -> None:
        assert is_auto_generated_personality(tmp_path / "ghost.md") is False


class TestFrontmatterCompatibility:
    """parse_personality must work whether or not frontmatter is present."""

    def test_parse_with_frontmatter_succeeds(self, tmp_path: Path) -> None:
        p = tmp_path / "auto.md"
        p.write_text(
            "---\n"
            "auto_generated: true\n"
            "---\n"
            "# Entity: Backend Eve\n"
            "## Identity\n"
            "- **Name**: dev.backend\n"
            "- **Role**: lead\n"
            "- **Model**: sonnet\n"
            "## System Prompt\n"
            "You are Eve. Methodical, prefers TDD.\n"
        )
        config = parse_personality(p)
        assert config.name == "dev.backend"
        assert config.role == "lead"
        assert config.model == "sonnet"
        assert "Methodical" in config.system_prompt


class TestSpawnWritesAutoPersonality:
    """create_team writes a file when both fields are present."""

    async def test_create_team_writes_auto_file_when_both_fields_present(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")

        await lifecycle_manager.create_team(
            "dev",
            "backend",
            display_name="Backend Eve",
            personality="Methodical, prefers TDD.",
        )

        path = tmp_path / "dev.backend.md"
        assert path.exists()
        text = path.read_text()
        assert text.startswith("---\nauto_generated: true\n---\n")
        assert "Backend Eve" in text
        assert "Methodical, prefers TDD." in text
        assert is_auto_generated_personality(path)

    async def test_create_team_skips_file_when_only_display_name(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        """Pair-or-nothing: missing personality means no file written."""
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")

        await lifecycle_manager.create_team(
            "dev", "backend", display_name="Backend Eve", personality=None
        )

        assert not (tmp_path / "dev.backend.md").exists()

    async def test_create_team_skips_file_when_only_personality(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")

        await lifecycle_manager.create_team(
            "dev", "backend", display_name=None, personality="Methodical."
        )

        assert not (tmp_path / "dev.backend.md").exists()

    async def test_create_team_does_not_overwrite_existing_file(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        """User-authored file at the target path must not be clobbered."""
        target = tmp_path / "dev.backend.md"
        target.write_text("# Entity: Hand-Authored\n## Identity\n- **Name**: dev.backend\n")
        original = target.read_text()

        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")

        await lifecycle_manager.create_team(
            "dev",
            "backend",
            display_name="Auto Eve",
            personality="Should not appear in file.",
        )

        assert target.read_text() == original

    async def test_create_team_loads_personality_into_lead_after_write(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        """Auto-written personality must also be loaded into the in-memory
        entity so the freshly-spawned lead has identity from birth (no
        manual ``/personality reload`` needed).
        """
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")

        lead = await lifecycle_manager.create_team(
            "dev",
            "backend",
            display_name="Backend Eve",
            personality="Methodical, prefers TDD.",
        )

        path = tmp_path / "dev.backend.md"
        assert lead.personality_path == path
        assert lead.system_prompt is not None
        assert "Methodical, prefers TDD." in lead.system_prompt

    async def test_create_team_skips_load_when_no_file_written(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        """When pair is incomplete, no file is written and no load happens.

        The lead's personality_path stays None and system_prompt stays empty.
        """
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")

        lead = await lifecycle_manager.create_team(
            "dev", "backend", display_name="Backend Eve", personality=None
        )

        assert lead.personality_path is None
        assert lead.system_prompt == ""


class TestKillCleansAutoPersonality:
    """kill_entity deletes auto-generated files but never user-authored ones."""

    async def test_kill_deletes_auto_generated_file(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")
        await lifecycle_manager.create_team(
            "dev",
            "backend",
            display_name="Backend Eve",
            personality="Methodical.",
        )
        path = tmp_path / "dev.backend.md"
        assert path.exists()

        await lifecycle_manager.kill_entity("dev.backend")

        assert not path.exists()

    async def test_kill_preserves_user_authored_file(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        """File without frontmatter is never deleted on kill."""
        # Pre-write a user-authored file at the target path
        target = tmp_path / "dev.backend.md"
        target.write_text("# Entity: User Wrote This\n## Identity\n- **Name**: dev.backend\n")
        original = target.read_text()

        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")
        # Spawn that hits the don't-clobber rule (file remains user-authored)
        await lifecycle_manager.create_team(
            "dev",
            "backend",
            display_name="Auto Eve",
            personality="Should not appear.",
        )

        await lifecycle_manager.kill_entity("dev.backend")

        assert target.exists()
        assert target.read_text() == original

    async def test_kill_when_no_personality_file_is_safe(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        """No file → no error; kill proceeds normally."""
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")
        await lifecycle_manager.create_team("dev", "backend")
        # No display_name/personality, so no file was written
        assert not (tmp_path / "dev.backend.md").exists()

        await lifecycle_manager.kill_entity("dev.backend")

        assert "dev.backend" not in lifecycle_manager.entities

    async def test_kill_team_deletes_auto_file_for_lead(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        """Cascading kill: the lead's auto file is cleaned up."""
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")
        await lifecycle_manager.create_team(
            "dev",
            "backend",
            display_name="Backend Eve",
            personality="Methodical.",
        )
        lead_path = tmp_path / "dev.backend.md"
        assert lead_path.exists()

        await lifecycle_manager.kill_team("dev", "backend")

        assert not lead_path.exists()


class TestActionDispatchWiresFieldsThrough:
    """The action dispatch loop must pass display_name/personality
    from the parsed Action through to create_team/spawn_worker.
    Otherwise the parser change is dead code.
    """

    async def test_spawn_team_action_writes_personality_file(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")

        action = Action(
            type="spawn_team",
            team_name="backend",
            display_name="Backend Eve",
            personality="Methodical.",
        )
        await lifecycle_manager._handle_actions("dev", "", [action])

        path = tmp_path / "dev.backend.md"
        assert path.exists()
        assert "Backend Eve" in path.read_text()
        # In-memory load reaches through the dispatch path, not just direct calls
        assert "Methodical." in lifecycle_manager.entities["dev.backend"].system_prompt

    async def test_spawn_worker_action_parses_as_unknown_and_writes_nothing(
        self, lifecycle_manager: ProcessManager, tmp_path: Path
    ) -> None:
        """The persistent Worker entity was retired in Ticket 018.

        ``spawn_worker`` is no longer a recognised action type: the parser
        skips it as a generic unknown action (no ``Action`` produced, an
        "Unknown action type" error reported). Dispatching the (empty)
        parsed actions therefore registers no worker and writes no
        personality file.
        """
        maestro = Maestro(name="dev", model="sonnet")
        lifecycle_manager._entities["dev"] = maestro
        lifecycle_manager.router.register("dev")
        await lifecycle_manager.create_team("dev", "backend")

        # The lead emits a spawn_worker block — now an unknown action.
        _clean, actions, errors = parse_actions(
            '<hive_actions>[{"type": "spawn_worker", '
            '"display_name": "Migrator Mig", "personality": "Cautious."}]'
            "</hive_actions>"
        )
        assert actions == []
        assert any("Unknown action type 'spawn_worker'" in err for err in errors)

        # Dispatching the parsed (empty) actions registers nothing.
        await lifecycle_manager._handle_actions("dev.backend", _clean, actions, parse_errors=errors)

        assert "dev.backend.w1" not in lifecycle_manager.entities
        assert not (tmp_path / "dev.backend.w1.md").exists()
