ALTER TABLE entities ADD COLUMN IF NOT EXISTS permission_mode TEXT NOT NULL DEFAULT 'default';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS loop_mode TEXT NOT NULL DEFAULT 'ralph';
ALTER TABLE entities ADD COLUMN IF NOT EXISTS current_priority INTEGER NOT NULL DEFAULT 3;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS worktree_path TEXT;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS task_id INTEGER;
